/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e2bfb0",
        "inverse-on-surface": "#f2f0f0",
        "inverse-primary": "#ffb693",
        "surface-container-high": "#e9e8e8",
        "primary-container": "#ff6b00",
        "on-error": "#ffffff",
        "surface-bright": "#faf9f9",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary-container": "#9a9999",
        "surface-container": "#efeded",
        "background": "#faf9f9",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-dim": "#dbdad9",
        "on-primary-fixed-variant": "#7a3000",
        "error-container": "#ffdad6",
        "surface-tint": "#a04100",
        "primary-fixed-dim": "#ffb693",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-error-container": "#93000a",
        "tertiary": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-secondary": "#ffffff",
        "on-primary-container": "#572000",
        "on-secondary-container": "#656464",
        "on-background": "#1b1c1c",
        "error": "#ba1a1a",
        "on-tertiary-container": "#313131",
        "primary-fixed": "#ffdbcc",
        "surface-variant": "#e3e2e2",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "secondary-fixed-dim": "#c8c6c5",
        "primary": "#a04100",
        "on-primary-fixed": "#351000",
        "inverse-surface": "#303031",
        "on-tertiary-fixed-variant": "#474747",
        "surface": "#faf9f9",
        "tertiary-fixed": "#e4e2e2",
        "secondary-fixed": "#e5e2e1",
        "secondary-container": "#e5e2e1",
        "surface-container-low": "#f5f3f3",
        "on-surface-variant": "#5a4136",
        "secondary": "#5f5e5e",
        "outline": "#8e7164",
        "on-secondary-fixed-variant": "#474646",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "80px",
        "container-max": "1280px",
        "base": "8px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      animation: {
        rotate: "rotate 0.5s linear infinite",
        bob: "bob 0.6s ease-in-out infinite alternate",
        wave: "wave 0.3s ease-in-out infinite alternate",
        "wheelie-anim": "wheelie-anim 1.8s ease-in-out forwards",
        "speed-fade": "speed-fade 0.2s linear infinite",
      },
      keyframes: {
        rotate: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        bob: {
          from: { transform: "translateY(0)" },
          to: { transform: "translateY(-5px)" },
        },
        wave: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(-15deg)" },
        },
        "wheelie-anim": {
          "0%, 100%": { transform: "rotate(0deg)" },
          "50%": { transform: "rotate(-15deg)" },
        },
        "speed-fade": {
          "0%": { opacity: "0", transform: "translateX(0)" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0", transform: "translateX(-100px)" },
        },
      },
    },
  },
  plugins: [],
}
